### ISSUE TITLE
Move this to your test func

### ISSUE THREAD

**Issue by anacrbraganca** [jutorres/twu-biblioteca-julianatorres#6]
https://github.com/jutorres/twu-biblioteca-julianatorres/blob/ee8f8c5b70770de137e5828fb3d9e15342484c22/src/test/java/com/twu/library/LibraryTest.java#L25

This code is part of the scope of your test... you could think at divide your test in 3 "blocks": 
- Setup
- Execution
- Assertions or verification

So, this code you introduced in setUp function is part of the setup part of your test.

**Comment by jutorres** [comment]
Resolved!
