### ISSUE TITLE
Make this function return a list

### ISSUE THREAD

**Issue by anacrbraganca** [jutorres/twu-biblioteca-julianatorres#7]
https://github.com/jutorres/twu-biblioteca-julianatorres/blob/ee8f8c5b70770de137e5828fb3d9e15342484c22/src/main/java/com/twu/library/Library.java#L16

Since the name of your function is getAvailableBooks you can return a list of available books instead of void. In this case, you could create another function to only print and inside this function use the getAvailableBooks to return the list of books you want to print.

Also, the test "testIfOnlyAvailableBooksAppearsInList" you can assert the size of books list that needs to considerate only available books.

You can reply the same behavior for unavailable books.

**Comment by jutorres** [comment]
Resolved and I refactored the code too! :)
